#!/usr/bin/env python3
"""build_canonical_backtest.py -- stitches backtest/rows_backfill.jsonl
(main) and backtest/rows_backfill_repair.jsonl (repair) into ONE canonical
dataset, backtest/rows_canonical.jsonl, per the reconciliation rule found
2026-08-25 while root-causing the 12 discrepant dates between the two.

ROOT CAUSE, precisely dated (not guessed): commit 919456e5 ("...fix a
backtest data-loss bug") fixed backtest/engine.py's to_row() --
`pick.get("raw_hit_probability", pick.get("hit_probability"))` only falls
back to hit_probability when the KEY IS ABSENT, but every candidate has
already set raw_hit_probability=None at construction, so the fallback never
fired. This wrote predicted_prob=None for every row on 7 of 13 markets
(home_run/total_bases/singles/doubles/triples/runs/rbis) whenever a
candidate's row was generated by CODE PREDATING that fix.

Every row this project generates now carries its own code_git_sha (see
backtest/engine.py's to_row()). Verified directly against both files: the
main backfill's early portion (2024-04-01..2025-02-26, 399,250 rows) is
tagged code_git_sha=c182b186, which predates 919456e5. Its LATER portion
(2025-02-27 onward) is tagged 6b748538, which postdates it -- no known
defect. The repair backfill covers exactly the same early range
(2024-04-01..2025-02-26) entirely under 6b748538 -- also postdates the fix,
also no known defect.

RECONCILIATION RULE, deterministic:
  - 2024-04-01 .. 2025-02-26: use REPAIR (post-fix code, full range covered)
  - 2025-02-27 onward:        use MAIN (post-fix code for this whole range)

This is not "repair wins because it has more rows" -- it is "prefer
whichever source is confirmed to run code downstream of the known
predicted_prob-nullification fix, for the date range where they overlap."
Verified directly, not assumed: every row this script keeps is checked
against KNOWN_GOOD_SHAS below and the run aborts if it finds an
unexpected/pre-fix sha in the range it was told to trust.

Also de-duplicates on the true canonical row identity
(date, game_pk, player_id, prop_type, needs) -- verified zero duplicates
exist in either source file as of this writing, but checked every run
rather than assumed to stay that way.

    /tmp/mlbvenv/bin/python3 backtest/build_canonical_backtest.py
"""
import json
import sys
from collections import Counter

MAIN_FILE = "/home/user/PROJECT-GRIDIRON/backtest/rows_backfill.jsonl"
REPAIR_FILE = "/home/user/PROJECT-GRIDIRON/backtest/rows_backfill_repair.jsonl"
OUT_FILE = "/home/user/PROJECT-GRIDIRON/backtest/rows_canonical.jsonl"

REPAIR_CUTOVER = "2025-02-26"  # inclusive: repair covers up to and including this date
KNOWN_GOOD_SHAS = {"6b748538"}  # postdates commit 919456e5; extend this set, don't just delete it, if a future audit confirms a newer sha is also clean
KNOWN_BAD_SHAS = {"c182b186"}   # predates 919456e5 -- predicted_prob nulled for 7 markets


def key(r):
    return (r["date"], r.get("game_pk"), r.get("player_id"), r.get("prop_type"), r.get("needs"))


def load(path):
    rows = []
    with open(path) as f:
        for line in f:
            rows.append(json.loads(line))
    return rows


def main():
    main_rows = load(MAIN_FILE)
    repair_rows = load(REPAIR_FILE)

    repair_keep = [r for r in repair_rows if r["date"] <= REPAIR_CUTOVER]
    main_keep = [r for r in main_rows if r["date"] > REPAIR_CUTOVER]

    bad_in_repair_keep = [r for r in repair_keep if r.get("code_git_sha") not in KNOWN_GOOD_SHAS]
    bad_in_main_keep = [r for r in main_keep if r.get("code_git_sha") not in KNOWN_GOOD_SHAS]
    if bad_in_repair_keep:
        print(f"ABORT: {len(bad_in_repair_keep)} repair rows in the kept range carry an "
              f"unexpected code_git_sha: {Counter(r.get('code_git_sha') for r in bad_in_repair_keep)}",
              file=sys.stderr)
        sys.exit(1)
    if bad_in_main_keep:
        print(f"ABORT: {len(bad_in_main_keep)} main rows in the kept range (>{REPAIR_CUTOVER}) "
              f"carry an unexpected code_git_sha: "
              f"{Counter(r.get('code_git_sha') for r in bad_in_main_keep)}", file=sys.stderr)
        sys.exit(1)

    dropped_main_bad = [r for r in main_rows if r["date"] <= REPAIR_CUTOVER
                        and r.get("code_git_sha") in KNOWN_BAD_SHAS]
    print(f"Dropping {len(dropped_main_bad)} main rows from the known-bad early range "
          f"(superseded by repair).")

    combined = repair_keep + main_keep
    seen = Counter(key(r) for r in combined)
    dupes = {k: c for k, c in seen.items() if c > 1}
    if dupes:
        print(f"ABORT: {len(dupes)} duplicate canonical keys across the stitched set "
              f"(showing up to 5): {list(dupes.items())[:5]}", file=sys.stderr)
        sys.exit(1)

    combined.sort(key=lambda r: (r["date"], str(r.get("game_pk") or ""),
                                 str(r.get("player_id") or ""),
                                 str(r.get("prop_type") or ""), str(r.get("needs") or "")))

    with open(OUT_FILE, "w") as f:
        for r in combined:
            f.write(json.dumps(r) + "\n")

    dates = sorted(set(r["date"] for r in combined))
    print(f"Wrote {len(combined)} canonical rows, {len(dates)} dates, "
          f"{dates[0]}..{dates[-1]} -> {OUT_FILE}")
    print(f"  from repair: {len(repair_keep)} rows ({REPAIR_FILE.rsplit('/',1)[-1]}, "
          f"<= {REPAIR_CUTOVER})")
    print(f"  from main:   {len(main_keep)} rows ({MAIN_FILE.rsplit('/',1)[-1]}, > {REPAIR_CUTOVER})")
    if len(main_keep) == 0:
        print("  NOTE: main contributed 0 rows -- main backfill has not yet reached "
              f"{REPAIR_CUTOVER} or has not completed. Re-run this script once it has "
              "progressed further; safe to re-run any time, fully deterministic.")


if __name__ == "__main__":
    main()
