#!/usr/bin/env python3
"""prob_subgroup_trust_report.py -- Priority 6, the first real accuracy
study run against canonical history (2026-08-25): "which predictions at the
SAME nominal probability are actually more/less trustworthy?"

WHY THIS QUESTION, NOT A DIFFERENT ONE: canonical_baseline_report.py already
showed the model's probability buckets are close to monotonically calibrated
in aggregate (predicted_prob >= 0.60 realizes ~66% overall). That pooled
number can hide real internal variance -- a 0.60-0.65 bucket built half from
a market/context where 0.60 really means 75% and half from one where it
means 50% would still average out to a plausible-looking 63%. This script
asks, WITHIN each probability bucket, does the realized hit rate vary in a
way that would let a future policy do better than trusting predicted_prob
alone.

WHAT IT DOES NOT DO: no --apply-policy fields (recommendation_status,
reliability, lineup-confirmation timing) exist in backtest/rows_canonical.jsonl
-- that data was generated by a default (non-policy-replay) run, exactly as
canonical_baseline_report.py's own evidence section documents as UNAVAILABLE.
This script segments only by fields that ARE present on every/most default
rows: prop_type (market), season_phase (RECONSTRUCTED from date, same rule
as canonical_baseline_report.py), fair_test, and actual_pa (opportunity)
buckets. cat_* component fields exist on only 3 of 13 markets (hits 69%,
hits_runs_rbis 46%, strikeouts 100%; zero elsewhere) -- deliberately NOT
segmented on here, since a market-inconsistent field would produce a
misleading "market" axis and a real "component quality" axis in one number.
That is scoped, documented future work, not fabricated here.

FLAGGING RULE: within a probability bucket, a subgroup is flagged as
"materially divergent" only if it has >= MIN_FLAG_N rows AND its hit rate
differs from the bucket's own overall hit rate by >= MIN_FLAG_DELTA. This is
descriptive, not a promotion signal -- per the standing instruction, do not
promote a change on this alone; it is the map for where Priority 7-11's
deeper causal work should look first.

    /tmp/mlbvenv/bin/python3 backtest/prob_subgroup_trust_report.py \
        backtest/rows_canonical.jsonl
"""
from __future__ import annotations

import json
import sys
from collections import defaultdict

sys.path.insert(0, __file__.rsplit("/", 1)[0] if "/" in __file__ else ".")
from canonical_baseline_report import prob_bucket, season_phase, load_rows

DEFAULT_PATH = "backtest/rows_canonical.jsonl"
MIN_FLAG_N = 200
MIN_FLAG_DELTA = 0.05


def pa_bucket(actual_pa):
    if actual_pa is None:
        return "unknown"
    if actual_pa <= 1:
        return "0-1_pa"
    if actual_pa <= 3:
        return "2-3_pa"
    if actual_pa <= 4:
        return "4_pa"
    return "5plus_pa"


def _rate(hits, n):
    return round(hits / n, 4) if n else None


def _axis_breakdown(rows, key_fn):
    buckets = defaultdict(lambda: {"n": 0, "hits": 0})
    for r in rows:
        b = buckets[key_fn(r)]
        b["n"] += 1
        b["hits"] += r["outcome"]
    return {k: {"n": v["n"], "hit_rate": _rate(v["hits"], v["n"])}
            for k, v in sorted(buckets.items(), key=lambda kv: str(kv[0]))}


def build_subgroup_report(rows):
    """rows must already be graded (outcome in (0,1)) with predicted_prob
    present -- caller filters, this function stays pure over what it's given."""
    by_prob_bucket = defaultdict(list)
    for r in rows:
        b = prob_bucket(r.get("predicted_prob"))
        if b is not None:
            by_prob_bucket[b].append(r)

    report = {}
    flags = []
    for bucket, bucket_rows in sorted(by_prob_bucket.items()):
        overall_n = len(bucket_rows)
        overall_hits = sum(r["outcome"] for r in bucket_rows)
        overall_rate = _rate(overall_hits, overall_n)

        axes = {
            "market": _axis_breakdown(bucket_rows, lambda r: r.get("prop_type") or "unknown"),
            "season_phase": _axis_breakdown(bucket_rows, lambda r: season_phase(r.get("date"))),
            "fair_test": _axis_breakdown(bucket_rows, lambda r: bool(r.get("fair_test"))),
            "opportunity_pa": _axis_breakdown(bucket_rows, lambda r: pa_bucket(r.get("actual_pa"))),
        }

        report[bucket] = {
            "overall_n": overall_n,
            "overall_hit_rate": overall_rate,
            "axes": axes,
        }

        for axis_name, breakdown in axes.items():
            for subgroup_value, stats in breakdown.items():
                if stats["n"] < MIN_FLAG_N or stats["hit_rate"] is None or overall_rate is None:
                    continue
                delta = round(stats["hit_rate"] - overall_rate, 4)
                if abs(delta) >= MIN_FLAG_DELTA:
                    flags.append({
                        "probability_bucket": bucket,
                        "axis": axis_name,
                        "subgroup": subgroup_value,
                        "n": stats["n"],
                        "subgroup_hit_rate": stats["hit_rate"],
                        "bucket_overall_hit_rate": overall_rate,
                        "delta": delta,
                    })

    flags.sort(key=lambda f: -abs(f["delta"]))
    return {"by_probability_bucket": report, "flagged_divergent_subgroups": flags}


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_PATH
    rows, n_malformed = load_rows(path)
    graded = [r for r in rows if r.get("outcome") in (0, 1) and r.get("predicted_prob") is not None]
    if not graded:
        print(f"No graded, priced rows read from {path} -- nothing to report.", file=sys.stderr)
        return 1
    report = build_subgroup_report(graded)
    report["_source_file"] = path
    report["_n_rows_considered"] = len(graded)
    report["_n_malformed_lines_skipped"] = n_malformed
    print(json.dumps(report, indent=2, sort_keys=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
