#!/usr/bin/env python3
"""provenance.py -- fail-fast regime detection for backtest datasets.

WHY THIS EXISTS: the 2026-08-25 repair-vs-main investigation found a real,
silent data-integrity risk -- backtest/rows_backfill.jsonl's early portion
was generated by code that predated a real bugfix (commit 919456e5), and
nothing detected this automatically. It was only caught because a human
happened to compare `code_git_sha` by hand across two files after noticing
a row-count discrepancy. That is not a repeatable safeguard. This module
makes it one: any script that loads a backtest dataset for analysis should
call `require_single_regime()` (or `inspect_regimes()` directly for a
report) before trusting the data, so an unannounced code/model regime mix
fails loudly instead of silently producing a biased comparison.

REGIME FIELDS INSPECTED (only ones actually present in the row schema
matter -- this does not fabricate a field that was never recorded):
  - code_git_sha: written by backtest/engine.py's to_row() on every row
    since it was added. The only regime signal that reliably exists in
    today's backtest rows.
  - model_version / feature_version / calibration_version /
    recommendation_policy_version / data_version: not currently written
    to backtest rows (these are live-pipeline/registry concepts -- see
    dashboard/publication_registry.py's VERSION_FIELDS), but inspected
    here too so this module keeps working without changes if a future
    backtest run starts recording them.

A row missing ALL regime fields is bucketed as ("unknown",) -- honestly
reported, never assumed to match anything else.

    /tmp/mlbvenv/bin/python3 backtest/provenance.py backtest/rows_backfill.jsonl
"""
import json
import sys
from collections import defaultdict

REGIME_FIELDS = (
    "code_git_sha", "model_version", "feature_version",
    "calibration_version", "recommendation_policy_version", "data_version",
)


class MixedRegimeError(Exception):
    """Raised by require_single_regime() when a dataset silently mixes
    incompatible code/model regimes and the caller did not explicitly opt
    into a regime-comparison analysis."""


def _regime_key(row):
    values = tuple(row.get(f) for f in REGIME_FIELDS)
    if all(v is None for v in values):
        return ("unknown",)
    return values


def inspect_regimes(path):
    """Scan a backtest JSONL file and report every distinct regime found.

    Returns a dict: {regime_key: {"n_rows": int, "dates": {min, max, count},
    "fields": {field_name: value, ...}}}. Never raises -- purely
    descriptive. Use require_single_regime() for the fail-closed gate."""
    regimes = defaultdict(lambda: {"n_rows": 0, "dates": set()})
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            key = _regime_key(row)
            regimes[key]["n_rows"] += 1
            d = row.get("date")
            if d:
                regimes[key]["dates"].add(d)

    report = {}
    for key, agg in regimes.items():
        dates = sorted(agg["dates"])
        report[key] = {
            "n_rows": agg["n_rows"],
            "n_dates": len(dates),
            "date_range": [dates[0], dates[-1]] if dates else None,
            "fields": dict(zip(REGIME_FIELDS, key)) if key != ("unknown",) else {},
        }
    return report


def require_single_regime(path, allow_multi=False):
    """Fail-closed gate: raises MixedRegimeError if `path` contains more
    than one distinct regime, UNLESS the caller passes allow_multi=True
    (an explicit, deliberate opt-in for a regime-COMPARISON analysis --
    e.g. measuring whether a code change itself affected outcomes -- which
    is a legitimate, different use case from an accuracy experiment that
    assumes one consistent dataset).

    Returns the single regime's report dict on success (or the full
    multi-regime report when allow_multi=True, so the caller can still see
    what it opted into)."""
    report = inspect_regimes(path)
    if len(report) <= 1 or allow_multi:
        return report
    lines = [f"MIXED REGIME DETECTED in {path}: {len(report)} distinct regimes found. "
             f"This dataset cannot be trusted for a single-regime accuracy experiment "
             f"without explicit acknowledgement (pass allow_multi=True if a regime "
             f"comparison is actually what you want)."]
    for key, info in sorted(report.items(), key=lambda kv: kv[1]["date_range"] or [""]):
        lines.append(f"  regime {key}: n_rows={info['n_rows']} n_dates={info['n_dates']} "
                     f"date_range={info['date_range']}")
    raise MixedRegimeError("\n".join(lines))


def main():
    if len(sys.argv) < 2:
        print("usage: provenance.py <rows.jsonl> [--allow-multi]")
        sys.exit(2)
    path = sys.argv[1]
    allow_multi = "--allow-multi" in sys.argv
    report = inspect_regimes(path)
    print(f"{path}: {len(report)} distinct regime(s) found")
    print("=" * 100)
    for key, info in sorted(report.items(), key=lambda kv: kv[1]["date_range"] or [""]):
        print(f"  regime {key}")
        print(f"    n_rows={info['n_rows']}  n_dates={info['n_dates']}  "
              f"date_range={info['date_range']}")
    print()
    try:
        require_single_regime(path, allow_multi=allow_multi)
        print("PASS: single regime (or --allow-multi was passed).")
    except MixedRegimeError as e:
        print(f"FAIL:\n{e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
