#!/usr/bin/env python3
"""Activation verifier for prospective V3 collection (prereg v3 section 16). Research only.

Prospective collection runs only when ALL of the following hold; the env var
or the file alone is never enough:
  * MLB_V3_ACTIVATION=JACOB_AUTHORIZED;
  * v3/ACTIVATION.json binds repository, PR 220, protocol V3, the exact v3 prereg
    commit + sha256, the exact implementation commit + v3 directory tree id, the
    authorizing Issue #91 comment id, and an activation timestamp;
  * the running checkout IS that implementation commit, with the same v3 tree and
    no local modifications under research/, and the prereg file hashes to the
    bound sha256;
  * the authorizing comment, fetched from the GitHub API by this code, is on Issue
    #91 of this repository, begins with "JACOB AUTHORIZATION: ALLOW", contains the
    phrase "V3 prospective activation", the full prereg commit, the prereg sha256
    and the full implementation commit, and carries no agent marker.
Any later code change makes the record stale (commit/tree mismatch). A record can
never authorize V4: protocol, prereg commit and prereg hash are fixed constants.

Known limitation (stated, not hidden): Jacob, Codex and Claude all post to GitHub
from the same account, so authorship cannot be proven from the API; the binding is
to the exact content of a server-timestamped #91 comment in Jacob's
authorization format, with agent-authored formats rejected.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import verify_evidence as VE  # noqa: E402

ACTIVATION_FILE = os.path.join(HERE, "ACTIVATION.json")
REPOSITORY = "werriesjacob1-cmyk/Full-Count"
PR_NUMBER = 220
PROTOCOL = "V3"
PREREG_PATH = "research/mlb_accuracy_challenger_prereg_v3_20261001.md"
V3_DIR = "research/mlb_accuracy_challenger_20261001/v3"
AGENT_MARKERS = ("Generated by [Claude Code]", "CLAUDE STATUS", "CODEX STATUS", "CODEX REVIEW", "REVIEW RESPONSE",
                 "SUPERCHAD AUDIT", "AGENT CLAIM")
REQUIRED_FIELDS = ("jacob_authorization_comment_id", "repository", "pr_number", "protocol_version",
                   "prereg_commit", "prereg_sha256", "implementation_commit", "implementation_tree",
                   "activation_timestamp")


def _git(repo, *a):
    return subprocess.check_output(["git", "-C", repo, *a], stderr=subprocess.DEVNULL).decode().strip()


def check_comment(comment, rec):
    body = (comment or {}).get("body") or ""
    first = next((ln.strip() for ln in body.splitlines() if ln.strip()), "")
    checks = {
        "on_issue_91": comment.get("issue_url") == f"https://api.github.com/repos/{REPOSITORY}/issues/91",
        "jacob_format": first == "JACOB AUTHORIZATION: ALLOW",
        "names_action": "v3 prospective activation" in body.lower(),
        "names_prereg_commit": VE.PREREG_COMMIT in body,
        "names_prereg_sha256": VE.PREREG_SHA256 in body,
        "names_implementation_commit": rec.get("implementation_commit", "~") in body,
        "no_agent_marker": not any(mk in body for mk in AGENT_MARKERS),
        "id_matches": str(comment.get("id")) == str(rec.get("jacob_authorization_comment_id")),
    }
    return checks


def verify_activation(repo_root, *, record=None, fetch=VE.fetch_issue_comment, env=None):
    """Returns (ok, reasons). Never raises for a mere refusal."""
    env = os.environ if env is None else env
    reasons = []
    if env.get("MLB_V3_ACTIVATION") != "JACOB_AUTHORIZED":
        reasons.append("ENV_NOT_SET")
    if record is None:
        if not os.path.exists(ACTIVATION_FILE):
            return False, reasons + ["NO_ACTIVATION_RECORD"]
        record = json.load(open(ACTIVATION_FILE))
    missing = [f for f in REQUIRED_FIELDS if not record.get(f)]
    if missing:
        return False, reasons + [f"MISSING_FIELDS:{missing}"]
    fixed = {"repository": REPOSITORY, "pr_number": PR_NUMBER, "protocol_version": PROTOCOL,
             "prereg_commit": VE.PREREG_COMMIT, "prereg_sha256": VE.PREREG_SHA256}
    reasons += [f"WRONG_{k.upper()}" for k, v in fixed.items() if record.get(k) != v]
    try:
        head = _git(repo_root, "rev-parse", "HEAD")
        tree = _git(repo_root, "rev-parse", f"HEAD:{V3_DIR}")
        dirty = [ln for ln in _git(repo_root, "status", "--porcelain", "--", "research/").splitlines()
                 if not ln.endswith(f"{V3_DIR}/ACTIVATION.json")]     # the untracked record itself
        prereg = VE.sha256_bytes(open(os.path.join(repo_root, PREREG_PATH), "rb").read())
    except (subprocess.CalledProcessError, OSError) as exc:
        return False, reasons + [f"CHECKOUT_UNREADABLE:{exc}"]
    if head != record["implementation_commit"]:
        reasons.append("CODE_COMMIT_NOT_AUTHORIZED")
    if tree != record["implementation_tree"]:
        reasons.append("CODE_TREE_NOT_AUTHORIZED")
    if dirty:
        reasons.append("LOCAL_MODIFICATIONS")
    if prereg != VE.PREREG_SHA256:
        reasons.append("PREREG_FILE_CHANGED")
    try:
        comment = fetch(record["jacob_authorization_comment_id"])
    except VE.EvidenceUnverified as exc:
        return False, reasons + [f"AUTHORIZATION_NOT_VERIFIABLE:{exc}"]
    failed = [k for k, ok in check_comment(comment, record).items() if not ok]
    reasons += [f"AUTHORIZATION_COMMENT_{k.upper()}" for k in failed]
    if comment.get("created_at") and record["activation_timestamp"] < comment["created_at"]:
        reasons.append("ACTIVATION_PREDATES_AUTHORIZATION")
    return not reasons, reasons
